from __future__ import annotations

from contextlib import redirect_stdout
import io
import json
from pathlib import Path
import sys
import unittest

TESTS = Path(__file__).resolve().parent
SKILL_ROOT = TESTS.parent
sys.path.insert(0, str(SKILL_ROOT / "scripts"))
sys.path.insert(0, str(TESTS))

from catalog import (  # noqa: E402
    CATALOG_FIELDS,
    GENERATED_OUTPUT_PATHS,
    assert_generated_outputs_current,
    build_catalog,
    build_generated_outputs,
    render_query_views,
    write_generated_outputs,
)
from corpus import load_corpus, validate_corpus  # noqa: E402
from fixture_factory import make_catalog_corpus, remove_tree  # noqa: E402
from generate_indices import main as generate_main  # noqa: E402
from kernelwiki_common import KernelWikiError  # noqa: E402


EXPECTED_QUERIES = TESTS / "fixtures" / "expected-queries"


class CatalogTests(unittest.TestCase):
    def setUp(self):
        self.roots: list[Path] = []

    def tearDown(self):
        for root in self.roots:
            remove_tree(root)

    def make_root(self) -> Path:
        root = make_catalog_corpus()
        self.roots.append(root)
        return root

    def outputs(self, root: Path) -> dict[str, bytes]:
        corpus = load_corpus(root)
        validate_corpus(corpus)
        return build_generated_outputs(corpus)

    def test_catalog_builder_is_sorted_card_only_and_deterministic(self):
        left = self.outputs(self.make_root())
        right = self.outputs(self.make_root())
        self.assertEqual(left, right)
        records = [json.loads(line) for line in left["compiled/catalog.jsonl"].splitlines()]
        self.assertEqual(
            ["pattern-launch-bound", "technique-kernel-fusion"],
            [record["id"] for record in records],
        )
        self.assertTrue(all(set(record) == set(CATALOG_FIELDS) for record in records))
        self.assertTrue(all(not record["id"].startswith("source-") for record in records))

    def test_catalog_record_resolves_provenance_versions_and_examples(self):
        corpus = load_corpus(self.make_root())
        validate_corpus(corpus)
        pattern = {record["id"]: record for record in build_catalog(corpus)}[
            "pattern-launch-bound"
        ]
        self.assertEqual(["local", "vllm-ascend"], pattern["source_repositories"])
        self.assertEqual(4, pattern["source_count"])
        self.assertEqual(
            (1, 1, 1),
            (
                pattern["positive_example_count"],
                pattern["counterexample_count"],
                pattern["capability_gap_count"],
            ),
        )
        self.assertEqual("claim-stale", pattern["version_claims"][0]["id"])
        self.assertEqual("stale", pattern["version_claims"][0]["status"])

    def test_all_nine_views_match_literal_goldens(self):
        views = render_query_views(load_corpus(self.make_root()))
        self.assertEqual(9, len(views))
        for relative_path, rendered in views.items():
            with self.subTest(path=relative_path):
                self.assertEqual(
                    (EXPECTED_QUERIES / Path(relative_path).name).read_bytes(), rendered
                )
                self.assertTrue(
                    rendered.startswith(
                        b"<!-- GENERATED by scripts/generate_indices.py; DO NOT EDIT. -->\n"
                    )
                )

    def test_write_replaces_drift_and_removes_stale_managed_files(self):
        root = self.make_root()
        outputs = self.outputs(root)
        write_generated_outputs(root, outputs)
        (root / "compiled/catalog.jsonl").write_bytes(b"drift\n")
        stale = root / "queries/stale.md"
        stale.write_text("stale\n", encoding="utf-8")
        write_generated_outputs(root, outputs)
        self.assertFalse(stale.exists())
        self.assertEqual(outputs["compiled/catalog.jsonl"], (root / "compiled/catalog.jsonl").read_bytes())
        assert_generated_outputs_current(root, outputs)

    def test_check_detects_modified_missing_and_extra_outputs(self):
        for mode in ("modified", "missing", "extra"):
            with self.subTest(mode=mode):
                root = self.make_root()
                outputs = self.outputs(root)
                write_generated_outputs(root, outputs)
                if mode == "modified":
                    (root / "queries/by-target.md").write_text("drift\n", encoding="utf-8")
                elif mode == "missing":
                    (root / "queries/by-target.md").unlink()
                else:
                    (root / "queries/extra.md").write_text("extra\n", encoding="utf-8")
                with self.assertRaisesRegex(KernelWikiError, "generated-drift"):
                    assert_generated_outputs_current(root, outputs)

    def test_write_rejects_incomplete_unknown_or_nonbyte_output_sets(self):
        root = self.make_root()
        outputs = self.outputs(root)
        cases = {
            "missing": {key: value for key, value in outputs.items() if key != "queries/by-target.md"},
            "unknown": {**outputs, "queries/unknown.md": b"x\n"},
            "nonbytes": {**outputs, "queries/by-target.md": "text"},
        }
        for label, payload in cases.items():
            with self.subTest(label=label):
                with self.assertRaisesRegex(
                    KernelWikiError, "generated-output-set|generated-output-bytes"
                ):
                    write_generated_outputs(root, payload)

    def test_generate_cli_write_then_check_smoke(self):
        root = self.make_root()
        stdout = io.StringIO()
        with redirect_stdout(stdout):
            self.assertEqual(0, generate_main(["--root", str(root)]))
        self.assertEqual(10, json.loads(stdout.getvalue())["generated"])
        stdout = io.StringIO()
        with redirect_stdout(stdout):
            self.assertEqual(0, generate_main(["--root", str(root), "--check"]))
        self.assertEqual(10, json.loads(stdout.getvalue())["checked"])

    def test_production_generated_set_is_exact_and_current(self):
        outputs = self.outputs(SKILL_ROOT)
        self.assertEqual(set(GENERATED_OUTPUT_PATHS), set(outputs))
        self.assertEqual(
            outputs,
            {path: (SKILL_ROOT / path).read_bytes() for path in GENERATED_OUTPUT_PATHS},
        )
        assert_generated_outputs_current(SKILL_ROOT, outputs)


if __name__ == "__main__":
    unittest.main()
